/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DomainModel.HoaDonModel;
import Service.HDCTIplm;
import Service.HDlmp;
import Service.Interface.HDSer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class HDForm extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private HDSer HDser = new HDlmp();
    private List<HoaDonModel> ListHD = new ArrayList<>();

    /**
     * Creates new form HDForm
     */
    public HDForm() {
        initComponents();
        TBbangHD.setModel(dtm);
        String[] headers = {"Mã HD", "Ngày Tạo", "Trạng Thái", "Mã NV", "Mã KH", "Mã KM"};
        dtm.setColumnIdentifiers(headers);
        ListHD = HDser.getAll();
        LoadData(ListHD);
    }

    private void LoadData(List<HoaDonModel> ListHDS) {
        dtm.setRowCount(0);
        for (HoaDonModel HD : ListHDS) {
            dtm.addRow(HD.toDataRow());
        }
    }

    private void showData(HoaDonModel Hd) {
        txtTrangThai.setText(String.valueOf(Hd.getTrangThai()));
        txtNgayTao.setText(Hd.getNgayTao());
        txtmaNV.setText(String.valueOf(Hd.getMaNV()));
        txtMaKH.setText(String.valueOf(Hd.getMaKH()));
        txtMaKM.setText(String.valueOf(Hd.getMaKM()));
    }

    public void ResetForm() {
        txtTrangThai.setText("");
        txtNgayTao.setText("");
        txtmaNV.setText("");
        txtMaKH.setText("");
        txtMaKM.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBbangHD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtmaNV = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtMaKM = new javax.swing.JTextField();
        BtUpdate = new javax.swing.JButton();
        BtReset = new javax.swing.JButton();
        BtCTHD = new javax.swing.JButton();
        BtAdd = new javax.swing.JButton();

        TBbangHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBbangHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBbangHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBbangHD);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Numbered list.png"))); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setText("Ngày Tạo :");

        jLabel3.setText("Trạng Thái :");

        jLabel4.setText("Mã NV :");

        jLabel5.setText("Mã KH :");

        jLabel6.setText("Mã KM :");

        txtNgayTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTaoActionPerformed(evt);
            }
        });

        BtUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Create.png"))); // NOI18N
        BtUpdate.setText("Update");
        BtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUpdateActionPerformed(evt);
            }
        });

        BtReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Refresh.png"))); // NOI18N
        BtReset.setText("Reset");
        BtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtResetActionPerformed(evt);
            }
        });

        BtCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Notes.png"))); // NOI18N
        BtCTHD.setText("Chi tiết hóa đơn");
        BtCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCTHDActionPerformed(evt);
            }
        });

        BtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Accept.png"))); // NOI18N
        BtAdd.setText("Add");
        BtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayTao)
                                    .addComponent(txtmaNV)
                                    .addComponent(txtMaKH)
                                    .addComponent(txtMaKM)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtUpdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(BtAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCTHD))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtCTHD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtUpdate)
                            .addComponent(BtReset))
                        .addGap(18, 18, 18)
                        .addComponent(BtAdd)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTaoActionPerformed

    private void BtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtResetActionPerformed
        // TODO add your handling code here:
        ResetForm();
        JOptionPane.showMessageDialog(this, "Reset");
    }//GEN-LAST:event_BtResetActionPerformed

    private void BtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUpdateActionPerformed
                HoaDonModel HD = ListHD.get(TBbangHD.getSelectedRow());
        String NgayTao = txtNgayTao.getText();
        String TrangThai = txtTrangThai.getText();
        String MaNV = txtmaNV.getText();
        String MaKH = txtMaKH.getText();
        String MaKM = txtMaKM.getText();
        HoaDonModel Hd = new HoaDonModel(NgayTao, Integer.valueOf(TrangThai), Integer.valueOf(MaNV), Integer.valueOf(MaKH), Integer.valueOf(MaKM));
        JOptionPane.showMessageDialog(this, HDser.suaHD(Hd, HD.getNgayTao()));
        ListHD = HDser.getAll();
        LoadData(ListHD);
    }//GEN-LAST:event_BtUpdateActionPerformed

    private void BtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddActionPerformed
        // TODO add your handling code here:
        String NgayTao = txtNgayTao.getText();
        String Trangthai = txtTrangThai.getText();
        String MaNV = txtmaNV.getText();
        String MaKH = txtMaKH.getText();
        String MaKM = txtMaKM.getText();
        HoaDonModel Hd = new HoaDonModel(NgayTao, Integer.valueOf(Trangthai), Integer.valueOf(MaNV), Integer.valueOf(MaKH), Integer.valueOf(MaKM));
        JOptionPane.showMessageDialog(this, HDser.add(Hd));
        ListHD = HDser.getAll();
        LoadData(ListHD);
    }//GEN-LAST:event_BtAddActionPerformed

    private void TBbangHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBbangHDMouseClicked
        // TODO add your handling code here:
        HoaDonModel Hdm = ListHD.get(TBbangHD.getSelectedRow());
        showData(Hdm);
    }//GEN-LAST:event_TBbangHDMouseClicked

    private void BtCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCTHDActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Show Chi tiết hóa Đơn !");
    }//GEN-LAST:event_BtCTHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdd;
    private javax.swing.JButton BtCTHD;
    private javax.swing.JButton BtReset;
    private javax.swing.JButton BtUpdate;
    private javax.swing.JTable TBbangHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTrangThai;
    private javax.swing.JTextField txtmaNV;
    // End of variables declaration//GEN-END:variables
}
