/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DomainModel.HoaDonModel;
import DomainModel.HoaDonModel2;
import Service.HDlmp;
import Service.Interface.HDSer;
import Service.Interface.IQlspService;
import Service.Interface.ThongKeService;
import Service.QlspImpl;
import Service.ThongKeIplm;
import ViewModel.DoanhThuView;
import ViewModel.Qlsp;
import ViewModel.hdview;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TRUNG DUC
 */
public class ThongKe extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel dcbmSort = new DefaultComboBoxModel();
    private HDSer hds = new HDlmp();
    private ThongKeService tks = new ThongKeIplm();

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();

        String[] headers = {"Mã HD", "Ngày tạo", "Tên NV", "Tên KH", "Mức khuyến mãi", "Trạng thái"};
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(headers);

        loadCBB();
        txtFirstDate.setVisible(false);
        lbTo.setVisible(false);
        txtLastDate.setVisible(false);
        btnTK.setVisible(false);

        loadDT(tks.getThongKe(""));

        loadHD(hds.getAllHdGdbh());

    }

    private void loadHD(ArrayList<hdview> list) {
        dtm.setRowCount(0);
        for (hdview x : list) {
            dtm.addRow(new Object[]{
                x.getMaHD(),
                x.getNgayTao(),
                x.getTenNv(),
                x.getTenKh(),
                x.getMucKm() + "%",
                x.hienTt()});
        }
    }

    private void loadCBB() {
        cbbSort.setModel(dcbmSort);
        dcbmSort.addElement("Moi thoi diem");
        dcbmSort.addElement("Trong ngay");
        dcbmSort.addElement("Trong tuan");
        dcbmSort.addElement("Tuan vua qua");
        dcbmSort.addElement("Trong thang");
        dcbmSort.addElement("Thang vua qua");
        dcbmSort.addElement("Ca nam");
        dcbmSort.addElement("Khoang thoi gian cu the");
    }

    private void loadDT(DoanhThuView dt) {
        txtDT.setText(String.valueOf(dt.getTongDoanhThu()));
        txtSP.setText(String.valueOf(dt.getTongSanPham()));
        txtHD.setText(String.valueOf(dt.getSoHoaDon()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbSort = new javax.swing.JComboBox<>();
        txtDT = new javax.swing.JLabel();
        txtSP = new javax.swing.JLabel();
        txtHD = new javax.swing.JLabel();
        txtFirstDate = new javax.swing.JTextField();
        txtLastDate = new javax.swing.JTextField();
        lbTo = new javax.swing.JLabel();
        btnTK = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Danh sách hóa đơn được lưu");

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/List.png"))); // NOI18N
        btnLoad.setText("Load data");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images/Price list.png"))); // NOI18N
        jLabel5.setText("Thống kê doanh thu");

        jLabel2.setText("Tổng doanh thu");

        jLabel3.setText("Số sản phẩm đã bán");
        jLabel3.setToolTipText("");

        jLabel4.setText("Số hóa đơn đã thanh toán");

        cbbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSortActionPerformed(evt);
            }
        });

        txtDT.setText("-.---.---");

        txtSP.setText("----");

        txtHD.setText("----");

        lbTo.setText("to");

        btnTK.setText("Thống kê");
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(88, 88, 88)
                                        .addComponent(txtDT))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHD)
                                            .addComponent(txtSP)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtFirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(lbTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLastDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoad)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnTK)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTo)
                    .addComponent(btnTK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSortActionPerformed
        if (cbbSort.getSelectedItem().equals("Khoang thoi gian cu the")) {
            txtFirstDate.setVisible(true);
            lbTo.setVisible(true);
            txtLastDate.setVisible(true);
            btnTK.setVisible(true);
        } else {
            txtFirstDate.setText("");
            txtLastDate.setText("");
            txtFirstDate.setVisible(false);
            lbTo.setVisible(false);
            txtLastDate.setVisible(false);
            btnTK.setVisible(false);
        }
        if (cbbSort.getSelectedItem().equals("Moi thoi diem")) {
            loadDT(tks.getThongKe(""));
        }
        if (cbbSort.getSelectedItem().equals("Trong ngay")) {
            loadDT(tks.getThongKe(" and hd.NgayTao = GETDATE()"));
        }
        if (cbbSort.getSelectedItem().equals("Trong tuan")) {
            loadDT(tks.getThongKe(" and DATEPART(WEEK, hd.NgayTao) = DATEPART(WEEK, GETDATE())"));
        }
        if (cbbSort.getSelectedItem().equals("Tuan vua qua")) {
            loadDT(tks.getThongKe(" and (hd.NgayTao > DATEADD(DAY, -8, GETDATE()) and hd.NgayTao <= GETDATE())"));
        }
        if (cbbSort.getSelectedItem().equals("Trong thang")) {
            loadDT(tks.getThongKe(" and MONTH(hd.NgayTao) = (MONTH(GETDATE()))"));
        }
        if (cbbSort.getSelectedItem().equals("Thang vua qua")) {
            loadDT(tks.getThongKe(" and (hd.NgayTao > DATEADD(DAY, -31, GETDATE()) and hd.NgayTao <= GETDATE())"));
        }
        if (cbbSort.getSelectedItem().equals("Ca nam")) {
            loadDT(tks.getThongKe(" and YEAR(hd.NgayTao) = (YEAR(GETDATE()))"));
        }
        if (cbbSort.getSelectedItem().equals("Khoang thoi gian cu the")) {
            txtFirstDate.setVisible(true);
            txtLastDate.setVisible(true);
        } else {
            txtFirstDate.setVisible(false);
            txtLastDate.setVisible(false);
            txtFirstDate.setText("");
            txtLastDate.setText("");
        }
    }//GEN-LAST:event_cbbSortActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        String first = "'" + txtFirstDate.getText() + "'";
        String last = "'" + txtLastDate.getText() + "'";
        loadDT(tks.getThongKe(" and (hd.NgayTao >= " + first + " and hd.NgayTao <= " + last));
    }//GEN-LAST:event_btnTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnTK;
    private javax.swing.JComboBox<String> cbbSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTo;
    private javax.swing.JLabel txtDT;
    private javax.swing.JTextField txtFirstDate;
    private javax.swing.JLabel txtHD;
    private javax.swing.JTextField txtLastDate;
    private javax.swing.JLabel txtSP;
    // End of variables declaration//GEN-END:variables
}
